language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi

script:
  - brew update
  - brew install python3
  - brew install lua51
  - brew install zsh
  - BASEDIR=$(pwd)
  - zsh test/test-zsh.zsh
  - which zsh
  - cd /usr/local
  - tar -cjf brew.tar.bz2 *
  - cd ${BASEDIR}
  - cp /usr/local/brew.tar.bz2 .

notifications:
  email:
    on_success: never
    on_failure: never

addons:
  artifacts: true
  s3_region: "us-east-1" # defaults to "us-east-1"
  paths:
  - brew.tar.bz2

